CREATE TABLE `users` (
    `id` INT(5) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `login` VARCHAR(30) NOT NULL UNIQUE,
    `password` VARCHAR(30) NOT NULL,
    `email` VARCHAR(30) NOT NULL UNIQUE,
    `name` VARCHAR(30) NOT NULL,
);